### ISSUE TITLE
Реализация команды на принудительную отмену игры

### ISSUE THREAD

**Issue by pulseneon** [pulseneon/tictactoe#11]
В боте есть реализованная команда ```/cancel game```. Нужно добавить её в главное меню, чтобы в случае непредвиденной ситуации всегда можно было выйти из игры с другим человеком.

**Comment by ilya34610** [comment]
Задача решена 
![image](https://user-images.githubusercontent.com/76793270/231673846-3e8bfa18-3e1b-4a8a-be8a-71f0b7d6b46f.png)
