### ISSUE TITLE
Перевод интерфейса на английский и немецкий

### ISSUE THREAD

**Issue by pulseneon** [pulseneon/tictactoe#12]
Требуется сделать перевод всех доступных языков с русского (основного) языка.

> Файл языка - это .yaml файл, который содержит в себе ```key:value``` словарь, который нужно локализировать

**Comment by ilya34610** [comment]
Перевод выполнен
![image](https://user-images.githubusercontent.com/76793270/233428339-7f858797-1f43-44f3-8618-c2cf80aabe9f.png)
![image](https://user-images.githubusercontent.com/76793270/233428399-1e2e5f08-23bc-48b5-a085-3368ac8cd355.png)

**Comment by pulseneon** [comment]
Найден баг с ошибкой вывода языка 
![image](https://user-images.githubusercontent.com/87504288/234062086-720dfc0c-f4a1-41fe-8747-d5596aac9a16.png)

**Comment by Kindhunt** [comment]
Перевод был пофикшен с релизом версии 1.0. Считаю тему закрытой.
