### ISSUE TITLE
Обработка ссылки на профиль

### ISSUE THREAD

**Issue by ilya34610** [pulseneon/tictactoe#5]
При поиске игрока по его телеграмм-нику  (_@пример_) не учитывается, что пользователь может отправить **ссылку** на профиль  (https://t.me/example)

**Comment by pulseneon** [comment]
Проблема была решена. 

![image](https://user-images.githubusercontent.com/87504288/230997874-ab0dc5fa-fe67-4e65-8aae-fd25a5e74d3f.png)
